### ISSUE TITLE
Sem vídeo

### ISSUE THREAD

**Issue by mauserr** [projeto-de-algoritmos/Grafo1_WIP#1]
Onde está o vídeo? Sem vídeo, sem avaliação.

**Comment by devsalula** [comment]
Boa Tarde Professor @mauserr , a gente cometeu um engano e submetemos o vídeo de apresentação via arquivo zip que enviamos pelo moodle. Peça desculpas pelo engano.
Mesmo não recebendo a avaliação submeti o vídeo de apresentação agora aqui na do repositório.
